### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by dworkin** [ChatTheatre/eOS-Doc#4]
In recent years, I have preferred different terms for concepts discussed herein.

- timeslice: _task_. Timeslice may be confusing, since "timeslicing" is a well-known term for interleaving the execution of multiple processes on a single CPU.
- statedump: _snapshot_

**Comment by noahgibbs** [comment]
That documentation has moved out of this repository and into the (much-modified from your own) ChatTheatre lpc-doc repository. I've fixed up "statedump" according to your recommendation, but retained an "a.k.a." since the term "statedump" is used so widely, including in the Kernellib. For timeslice, I've mentioned the term "task" but basically just said that both terms are ambiguous and there is no non-ambiguous term for it. Certainly saying a "task" isn't going to mean this to developers from other languages. But then, other than perhaps Node.js developers, few people are going to be familiar with the concept already at all.

But "task" is very frequently used as a synonym for "process" in the sense of a Unix/OS process. So it's definitely ambiguous as well :-/

In any case, I'll be sure to mention the term "task" since that may help them recognise the same idea in the future, and I'll try to mention it where relevant in future documentation.

**Comment by dworkin** [comment]
Re _task_: fair enough, task is ambiguous, but I will refer to them as tasks in my own writings. I've tried to use less ambiguous terms like _execution round_ but found them unsatisfying in the end.

**Comment by noahgibbs** [comment]
Entirely fair. And yes, timeslice certainly has similar problems.

**Comment by dworkin** [comment]
I've checked the changes in the pull request for lpc-doc, and they look good to me.
